Repository Daniflav94/App-bibliotech, pull requests merged in 2022-11, with the labels that each got.

#19 notification Service
  angular.json
  src/app/service/notification.service.ts
Labels: enhancement

#20 pagina-emprestimo
  src/app/app.component.html
  src/app/app.module.ts
  src/app/views/novo-emprestimo/novo-emprestimo.component.css
  src/app/views/novo-emprestimo/novo-emprestimo.component.html
  src/app/views/novo-emprestimo/novo-emprestimo.component.ts
  src/custom-theme.scss
Labels: enhancement

#22 Login
  src/app/app.component.html
  src/app/views/login/login.component.css
  src/app/views/login/login.component.html
  src/assets/icons/icons8-google-logo.svg
  src/assets/images/img-login.png
Labels: enhancement

#23 página novo-cadastro estilizada
  src/app/app.component.html
  src/app/views/login/login.component.css
  src/app/views/novo-cadastro/novo-cadastro.component.css
  src/app/views/novo-cadastro/novo-cadastro.component.html
Labels: enhancement

#24 Service emprestimos criado, lógica para criar empréstimos no banco de…
  src/app/app.component.html
  src/app/app.module.ts
  src/app/models/emprestimo.ts
  src/app/service/emprestimos.service.ts
  src/app/views/novo-emprestimo/novo-emprestimo.component.css
  src/app/views/novo-emprestimo/novo-emprestimo.component.html
  src/app/views/novo-emprestimo/novo-emprestimo.component.ts
  src/assets/icons/icone-google-colorido.svg
Labels: enhancement

#25 Criação do HTML e CSS do dashboard
  src/app/app.component.html
  src/app/app.module.ts
  src/app/views/dashboard/dashboard.component.css
  src/app/views/dashboard/dashboard.component.html
  src/app/views/dashboard/dashboard.component.ts
  src/assets/images/dashboard-fundo.png
  src/assets/images/dashboard-fundo1.png
Labels: enhancement

#26 Autenticacao/criação
  src/app/app.component.html
  src/app/app.module.ts
  src/app/models/user.ts
  src/app/service/auth.service.ts
  src/app/views/login/login.component.html
  src/app/views/login/login.component.ts
  src/app/views/novo-cadastro/novo-cadastro.component.html
  src/app/views/novo-cadastro/novo-cadastro.component.ts
Labels: enhancement

#29 Página que lista os livros feita, página de login corrigida, adiciona…
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/views/adicionar-livro/adicionar-livro.component.css
  src/app/views/adicionar-livro/adicionar-livro.component.html
  src/app/views/adicionar-livro/adicionar-livro.component.ts
  src/app/views/dashboard/dashboard.component.css
  src/app/views/dashboard/dashboard.component.html
  src/app/views/home/home.component.html
  src/app/views/livros/livros.component.css
  src/app/views/livros/livros.component.html
  src/app/views/livros/livros.component.ts
  src/app/views/login/login.component.css
  src/app/views/login/login.component.html
  src/app/views/novo-cadastro/novo-cadastro.component.css
  src/app/views/novo-cadastro/novo-cadastro.component.html
Labels: enhancement

#31 Atualização service new livro
  src/app/app.component.html
  src/app/models/livro.ts
  src/app/service/livros.service.ts
  src/app/views/livros/livros.component.html
  src/app/views/livros/livros.component.ts
  src/app/views/login/login.component.ts
Labels: bug, enhancement

#32 ajuda do prof
  src/app/app.component.html
  src/app/service/auth.service.ts
  src/app/service/emprestimos.service.ts
  src/app/service/livros.service.ts
  src/app/views/login/login.component.ts
Labels: bug

#34 Dashboard
  src/app/componente/header/header.component.css
  src/app/componente/header/header.component.html
  src/app/views/dashboard/dashboard.component.html
  src/app/views/dashboard/dashboard.component.ts
Labels: enhancement

#37 Guard
  src/app/app-routing.module.ts
  src/app/guards/auth.guard.ts
  src/app/service/livros.service.ts
  src/app/views/adicionar-livro/adicionar-livro.component.css
  src/app/views/adicionar-livro/adicionar-livro.component.html
  src/app/views/adicionar-livro/adicionar-livro.component.ts
  src/app/views/dashboard/dashboard.component.html
  src/app/views/editar-emprestimo/editar-emprestimo.component.ts
  src/app/views/home/home.component.html
  src/app/views/livros/livros.component.html
  src/app/views/login/login.component.html
Labels: enhancement

#38 Details
  src/app/app.module.ts
  src/app/componente/details/details.component.css
  src/app/componente/details/details.component.html
  src/app/componente/details/details.component.ts
  src/app/models/emprestimo.ts
  src/app/views/adicionar-livro/adicionar-livro.component.ts
  src/app/views/dashboard/dashboard.component.css
  src/app/views/dashboard/dashboard.component.html
  src/app/views/dashboard/dashboard.component.ts
Labels: enhancement

#39 Atualização
  src/app/service/livros.service.ts
  src/app/views/adicionar-livro/adicionar-livro.component.css
  src/app/views/adicionar-livro/adicionar-livro.component.html
  src/app/views/adicionar-livro/adicionar-livro.component.ts
  src/app/views/editar-emprestimo/editar-emprestimo.component.ts
  src/app/views/home/home.component.html
  src/app/views/livros/livros.component.ts
Labels: bug

#40 Melhorias scroll
  src/app/views/adicionar-livro/adicionar-livro.component.css
  src/app/views/dashboard/dashboard.component.css
  src/app/views/livros/livros.component.css
  src/app/views/novo-emprestimo/novo-emprestimo.component.css
Labels: enhancement
